version: '2'

services:
    node:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: wmde/wikibase-rest-api-proposal
        volumes:
            - '~/.npm:/.npm'
            - './:/app'
        working_dir: /app
        environment:
            - NODE_ENV
            - NODE_DEBUG
    ui:
      extends:
        service: node
      ports:
        - '${UI_PORT}:8080'
      command: 'npm run watch -- --host 0.0.0.0'
